version: '3'

services:
  authgoapp:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    volumes:
      - ./auth:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - AUTH_PORT=8080
      - REDIS_ADDR=redis:6379
      - JWT_SECRET_KEY=sua_chave_secreta
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
